### ISSUE TITLE
Re-introduce a commandline version of the service that works on Linux/Mac

### ISSUE THREAD

**Issue by encratite** [encratite/RiotControl#23]
An acquaintance of mine has already requested that I make this service work with Linux servers again. Right now the core service has a WPF GUI so it won't run with Mono and it is unlikely that it works with Wine, too. It's fairly easy to separate the GUI code from the rest of the services. Perhaps this could be added as a separate project file which simply reuses the most important source files from the main project.

I just got another request from Reddit, this time for Mac, from user "Metalhawk".

**Comment by kumouri** [comment]
Separating the GUI code from the core implementation would probably also help with running the server in the background. It would allow the server to be more easily run from the command line on Windows, as well, which would allow the user to start it up using a script to have it run in the background.

**Comment by encratite** [comment]
Well, I don't think that most Windows users are interested in running it as a commandline application. They probably want it to be concealed in the Tray instead, readily returning to its GUI form on demand. I might give this a go today.

**Comment by kumouri** [comment]
Possibly, although I think most users are more interested in the GUI in the browser than the server GUI. I'll be looking at the code today (just found the program last night and thought I'd look at the issues section to see if I could help) and tomorrow, so I'll see what I can do.

**Comment by encratite** [comment]
I've managed to work RiotShield on Linux with Mono. I'd like to see this on MacOS, too. See:

http://riot.control-c.ir/#RiotShield
