### ISSUE TITLE
Add an option to automatically launch the application when Windows starts

### ISSUE THREAD

**Issue by encratite** [encratite/RiotControl#25]
This was brought up by "netonex" on Reddit. It could easily be achieved by adding a registry entry somewhere. I'm currently checking up on it. The most convenient way would probably be a key that makes it show up in msconfig. The most convenient way to achieve that is HKCU\Software\Microsoft\Windows\CurrentVersion\Run, I believe.

**Comment by ishashobar** [comment]
you could always just add a shortcut to the program in the Startup folder.

**Comment by encratite** [comment]
That's even more complicated than editing the registry.

**Comment by encratite** [comment]
Implemented in https://github.com/epicvrvs/RiotControl/commit/801b0e9b09c072be9b6eebde82b0154b964522da
