### ISSUE TITLE
The application should be able to run in the background

### ISSUE THREAD

**Issue by encratite** [encratite/RiotControl#26]
Many users might be annoyed by the application constantly being visible in the taskbar while it is running. They are used to applications providing options so they can be reduced to running in the tray, without having a window. I've never messed with the tray before but I'm told it's annoying.

**Comment by Banana-no-ana** [comment]
I'll check this one out

**Comment by encratite** [comment]
Slacker, you didn't do anything!

Implemented in https://github.com/epicvrvs/RiotControl/commit/bea3ce332c4cb00a8877e388d2ae993ef98c4340
