### ISSUE TITLE
Privileges and the web interface

### ISSUE THREAD

**Issue by encratite** [encratite/RiotControl#40]
Reddit user "GooMi5" reports that there are cases when non-privileged users access the service and get silent exceptions thrown in the background when they attempt to perform a search. I thought I had tested this thoroughly and it should not even render the search menu for a non-privileged user - but I might be wrong.

Maybe somebody can check on this at some point. I haven't even tried to reproduce this in the current version yet.

**Comment by GooMiS** [comment]
Here's my setup and steps how I can simply reproduce the issue.
PC (port 80 handling opened in the firewall) - Router (port 80 requests forwarded to local PC adress) - Internet

I'm putting my local IP in:

```
[Web][Host]IP[/Host]...[/Web]
```

Adding local IP to privileged adresses list. (leaving the defaults, just adding a new one)
When I access the webserver via local adress all goes fine.
But when I try to access it using public IP it still renders search form and after performing a search just hangs on "Searching for ..." throwing:

---

<pre>
------------
RiotControl.js:42 GET http://goomis.dyndns.org/API/Search/EUNE/goomis 400 (Bad request)
RiotControl.js:42 apiCall
RiotControl.js:670 apiFindSummoner
RiotControl.js:1285 performSearch
RiotControl.js:807 searchFunction
RiotControl.js:812 summonerNameField.onkeydown
------------
RiotControl.js:38 Uncaught API error in /API/Search/EUNE/goomis: You do not have the permission to use this service (400)
RiotControl.js:38 request.onreadystatechange
------------
</pre>

---

tested on r252
hope this helps

**Comment by encratite** [comment]
https://github.com/epicvrvs/RiotControl/commit/4c204e2d293e57969b840feca335a9a255a660b2
