### ISSUE TITLE
Inform the user if they can't perform a query

### ISSUE THREAD

**Issue by encratite** [encratite/RiotControl#43]
From Uhkis:

When trying to query for a summoner from ip that is not in the PrivilegedAddresses, the query page just says "Loading" and "gets stuck". User should be informed "You are not able to make a query" .

**Comment by Uhkis** [comment]
Duplicate of https://github.com/epicvrvs/RiotControl/issues/40

**Comment by encratite** [comment]
Fixed in https://github.com/epicvrvs/RiotControl/commit/4c204e2d293e57969b840feca335a9a255a660b2
