### ISSUE TITLE
WPF version is showing a white screen in browser

### ISSUE THREAD

**Issue by Uhkis** [encratite/RiotControl#48]
Several users are getting a white screen in browser with the WPF version. Output tab isn't showing any erorrs.

Javascript error log: 

Timestamp: 6.4.2012 19:02:30
Error: uncaught exception: Invalid cookie format

**Comment by encratite** [comment]
Yeah, sorry about this one, I hadn't considered the case where the cookie was unset after I had already set it so the bug no longer occurred in my local development version.

Fixed in https://github.com/epicvrvs/RiotControl/commit/fc72b7712432db47292dec75d15abf3af384a20f
