### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by mawhidby** [encratite/RiotControl#54]
After installing successfully and getting application to work I get the message: "You are running Riot Control r285 but you need at least r323 to use this system." when trying to run. This has happened a couple of times after reinstalling now

**Comment by encratite** [comment]
Uhm this sounds like you are in fact running an old version of Riot Control. Use the files from from the new RiotControl.zip and just copy your existing RiotControl.sql there. Edit the new Configuration.xml and copy your logins from the old Configuration.xml there. If the problem persists, join our chat:

http://riot.control-c.ir/#chat
