### ISSUE TITLE
Update Launches ASUSUpdate, fails.

### ISSUE THREAD

**Issue by wispborne** [encratite/RiotControl#58]
If ASUSUpdate is installed (for flashing BIOS from desktop), the Updater will launch it and then do nothing, rather than updating RiotControl. Manual update is required.

**Comment by encratite** [comment]
This sounds utterly bizarre. Come back on IRC so we can discuss this.

It may be caused by RiotControl using Update.exe instead of .\Update.exe but I thought the local directory should always have precedence...

**Comment by encratite** [comment]
Fixed in https://github.com/epicvrvs/RiotControl/commit/00e0bea08b9fb9249b1a80a4b0033b55c66832b1
