### ISSUE TITLE
Looking up the account signed in with causes the client to disconnect.

### ISSUE THREAD

**Issue by ghost** [encratite/RiotControl#68]
--Looking up the account signed in with causes the client to disconnect.--

The title says it all.

**Comment by encratite** [comment]
Yeah, the underlying library for this, LibOfLegends/FluorineFx, just don't work properly or it might be a server filter that is supposed to kill off clients that have bot-like query patterns. I'm probably not going to fix this. Jabe says it works fine with his Java library, even when he hammers the servers.
