### ISSUE TITLE
Trying to Contact Owner

### ISSUE THREAD

**Issue by mastergberry** [encratite/RiotControl#73]
Hey, I spoke with you on IRC a week or two ago.  Trying to still extract all the images from the client, and I know you said you had a Ruby script.  Was hoping to acquire a copy of said script :)  Only thing I have been able to do is to extract the images from swf files but they do not retain the image names properly...

Maybe I am looking in the wrong section, but for instance the profile icons (buddy icons) only seem to be in those swf files.

Can you email me admin [at] lolsummoners [dot] com ?

Thanks

**Comment by encratite** [comment]
Oh, that script used a manual SQL export of the data from the SQLite databases that contain this stuff. Unluckily my fully automated approach didn't work either and several files were missing in the Air client so I had to manually obtain pictures for them from another source. I haven't automated the acquisition of champion pictures either, I've been doing that manually lately. I know that some of these pictures are apparently only available from the SWF files and no unluckily I don't know how to extract them automatically. Maybe the PBE client has a better format for this.
