### ISSUE TITLE
MySQL Seems to be causing errors.

### ISSUE THREAD

**Issue by confuz3d** [encratite/RiotControl#77]
Hi, i've tried using a MySql database instead of the integrated sqlite flatfile db.

``` XML
<DatabaseProvider>MySql.Data.MySqlClient</DatabaseProvider>
<Database>Datasource=127.0.0.1;user=Bob;password=*******;Database=riotcontrol</Database>
```

I have those 2 lines in configuration.xml and RiotControl successfully connect to my database. BUT, whenever i try to search for a summoner, I get an API error and the page freezes there and the search form is disabled.

If you need any more informations on my setup i'll provide them. I can use the sqlite DB for a moment, but i'd really prefer being able to use a MySql database as it is easier to manage and tweak.

This is the error chrome gives me:
 Failed to load resource: the server responded with a status of 500 (Internal server error) http://MYDOMAIN:8123/API/Search/NA/confuzed
Uncaught API error in /API/Search/NA/confuzed: Internal server error (500)

**Comment by encratite** [comment]
Did you create the tables using the appropriate SQL file?

https://github.com/epicvrvs/RiotControl/blob/master/Database/MySQL.sql

RiotControl doesn't do that on its own. In the case of MySQL and PostgreSQL a lot of manual labour is involved. Anyways, if you did that and it still breaks, you really need to debug the application while this is happening (probably in Visual Studio).

**Comment by confuz3d** [comment]
Yep, the database is there with all the tables and when i search for a summoner it adds basic infos in the "summoner" table but it also duplicates the entry if I search the same name more than one time which is weird.

I've switched my database to PostgreSQL and it works perfectly. I'd like to be able to use MySQL tho as i know nothing on how PostgreSQL works xD I'll go and try debugging and see if I can identify the problem.

Thanks for the quick answer, and thank you for this awesome piece of software :)

This question might be stupid, be rude on me if its necessary :smile: The RiotControl.exe.config file has 2 entries, one for Npgsql and one for SQLite, should i add MySQL in there for it to work properly? Or is it not needed for mysql for some reasons? (Sorry i'm a total noob when it comes to .NET stuff ¬¬')
